"""Add firstname lastname to user and password_reset_tokens rel

Revision ID: 7774af2cabc0
Revises: 
Create Date: 2025-06-30 00:40:02.613857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7774af2cabc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER', sa.Column('firstname', sa.String(), nullable=False))
    op.add_column('USER', sa.Column('lastname', sa.String(), nullable=False))
    op.drop_column('USER', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('USER', 'lastname')
    op.drop_column('USER', 'firstname')
    # ### end Alembic commands ###
