"""add is_active and verification columns to USER

Revision ID: cd2158d447e4
Revises: 7774af2cabc0
Create Date: 2025-06-30 02:00:40.710524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd2158d447e4'
down_revision: Union[str, Sequence[str], None] = '7774af2cabc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER') as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('verification_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('code_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('USER') as batch_op:
        batch_op.drop_column('code_expires_at')
        batch_op.drop_column('verification_code')
        batch_op.drop_column('is_active')
    # ### end Alembic commands ###
